export enum EventType {
  SALE_CREATED = 'SALE_CREATED',
  PURCHASE_RECEIVED = 'PURCHASE_RECEIVED',
  STOCK_ADJUSTED = 'STOCK_ADJUSTED',
  PAYMENT_MADE = 'PAYMENT_MADE',
  RETURN_PROCESSED = 'RETURN_PROCESSED',
}
